# remove first and last line, using it as markers in file
        terminationMessagePolicy: File
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: hive-sec
              key: hiveToken
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: honey-config
          items:
          - key: honey.cfg
            path: honey.cfg
      dnsPolicy: ClusterFirst
