# update deployment with secret, volumeMounts and volumes
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: hive-sec
              key: hiveToken
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        ConfigMap:
          name: honey-config
          items:
            - key: honey.cfg
              path: honey.cfg
  
