# Troubleshooting steps

# command shortcuts
k=kubectl

# Bash alias
alias k='kubectl' alias kdro='kubectl --dry-run=client -o yaml' alias kto='kubectl config set-context $(kubectl config current-context)' alias kat='kubectl config get-contexts'

# imperative create configmap
kubectl create configmap kenobi --namespace=yoda --from-literal=planet=hoth

# imperative mount configmap dry run
kubectl create pod chewie --namespace=yoda --image=nginx:stable --dry-run=client -o yaml > pod.yaml

kubectl run chewie --image=nginx:stable --namespace=yoda --dry-run=client -o yaml > pod.yaml

k run chewie --image-nginx:stable -n yoda --dry-run=client -o yaml > chewie.yml

# undo rollout or rollback
kubectl rollout undo deployment/fish

# PersistentVolume
kubectl create pv my-pv --save-config --dry-run=client -o yaml > pv.yaml


# Basic Pod information
kubectl get pods

# More information related to Pod
kubectl describe pod <pod-name>

#Listing containers in a pod
kubectl get pod web-frontend-7b46597bcf-xnkhb -o jsonpath='{.spec.containers[*].name}' -n hive

# Describe a deployment
k describe deployment auth-frontend -n comb

# Get a particular deployment information
k get deployment users-rest -n hive

# deployment edit error msg
# below error due to indentation of the last line
cloud_user@k8s-control:~$ k apply -f honey-config.yml 
error: error parsing honey-config.yml: error converting YAML to JSON: yaml: line 9: could not find expected ':'
cloud_user@k8s-control:~$ cat honey-config.yml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: honey-config 
  namespace: hive
data: 
  honey.cfg: |
  There is always money in the honey stand!
cloud_user@k8s-control:~$

# error editing deployment hive-mgr
cloud_user@k8s-control:~$ k edit deployment hive-mgr -n hive
error: deployments.apps "hive-mgr" is invalid


